### ISSUE TITLE
Integers should be allowed as floats

### ISSUE THREAD

**Issue by studds** [wmfs/j2119#37]
I'm using https://github.com/wmfs/statelint to validate a schema, raising this issue here because I think the issue is here and not in that project.

I'm validating the following state machine definition with statelint:

```
{
    "Comment": "State machine for demonstrating the problem",
    "StartAt": "Start",
    "TimeoutSeconds": 3600,
    "States": {
        "Start": {
            "Type": "Task",
            "Resource": "arn:aws:lambda:REGION:ACCOUNT_ID:function:FUNCTION_NAME",
            "Retry": [
                {
                    "ErrorEquals": ["States.ALL"],
                    "IntervalSeconds": 60,
                    "MaxAttempts": 5,
                    "BackoffRate": 2.0
                }
            ],
            "End": true
        }
    }
}

```

### Expected outcome

Should pass linter with no errors.

### Actual outcome

I get this error: State Machine.States.Start.Retry[0].BackoffRate is 2 but should be a Float

**Comment by jezhiggins** [comment]
I think this mirrors the behaviour of the Amazon Labs' original. However, I agree that it feels like the wrong thing to do.

**Comment by jezhiggins** [comment]
New statelint released as well - see @wmfs/statelint/releases/tag/v1.7.1

**Comment by studds** [comment]
Thanks for the prompt fix!
